import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ContentSection from "@/components/ContentSection";

export default function Terms() {
    return (
        <div className="min-h-screen flex flex-col font-serif">
            <Header />

            <main className="flex-grow px-6 pt-32">
                <section className="text-center mb-16 animate-fade-in">
                    <h1 className="text-3xl md:text-4xl font-sans font-bold text-gray-900 mb-4">Terms of Service</h1>
                    <p className="text-gray-500">Last updated: 2025</p>
                </section>

                <ContentSection title="1. Introduction" delay="0.2s">
                    <p>
                        Welcome to Iknowledge. By accessing or using our website and ecosystem, you agree to be bound by these Terms of Service. Iknowledge is an ecosystem designed to facilitate the creation, discovery, and utilization of specialized AI Agents.
                    </p>
                </ContentSection>

                <ContentSection title="2. The Ecosystem" delay="0.4s">
                    <p>
                        Iknowledge provides a platform where developers can deploy specialized Agents and users can discover and interact with them. We strive to minimize transaction costs and maximize the efficiency of matching problems with the right AI solutions.
                    </p>
                </ContentSection>

                <ContentSection title="3. User Conduct" delay="0.6s">
                    <p>
                        You agree to use the Iknowledge ecosystem responsibly. You must not use our services or the Agents within our ecosystem for any illegal, harmful, or unethical activities. This includes, but is not limited to, generating hate speech, facilitating cyberattacks, or violating the privacy of others.
                    </p>
                </ContentSection>

                <ContentSection title="4. Intellectual Property" delay="0.8s">
                    <p>
                        The Iknowledge platform, including its design, code, and branding, is the property of Iknowledge. Individual Agents within the ecosystem may be subject to their own specific license agreements and intellectual property rights as defined by their respective developers.
                    </p>
                </ContentSection>

                <ContentSection title="5. Disclaimers" delay="1.0s">
                    <p>
                        Agents within the Iknowledge ecosystem are powered by Large Language Models (LLMs) and other software programs. We do not guarantee the accuracy, reliability, or safety of the outputs generated by these Agents. You use them at your own risk. Iknowledge is not liable for any damages arising from the use of these Agents.
                    </p>
                </ContentSection>
            </main>

            <Footer />
        </div>
    );
}
